### ISSUE TITLE
Segmentation fault in gdImageFlipVertical()

### ISSUE THREAD

**Issue by smcdow** [libgd/libgd#147]
When I use `gdImageFlipVertical()` against an image created with `gdImageCreate()`, I'm getting a segfault.  This does not happen when I use `gdImageCreateTrueColor()` to create the image.

Here's my test code:
```
#include <stdio.h>
#include "gd.h"

int main () 
{
  gdImagePtr im;
  int black;
  int white;

  int imageSize = 800;
  im = gdImageCreate(imageSize, imageSize);
  black = gdImageColorAllocate(im, 0, 0, 0);  
  white = gdImageColorAllocate(im, 255, 255, 255);  

  gdImageLine(im, 0, 0, imageSize-1, imageSize-1, white);
  gdImageLine(im, 0, imageSize-1, imageSize/2, 0, white);

  FILE *out;

  out = fopen("foo.gif", "wb");
  printf("writing foo.gif\n");
  gdImageGif(im, out);
  fclose(out);
  
  gdImageFlipVertical(im);

  out = fopen("foo-inv.gif", "wb");
  printf("writing foo-inv.gif\n");
  gdImageGif(im, out);
  fclose(out);

  gdImageDestroy(im);
  
  return 0;
}
```

Debugging session follows:
```
(gdb) bt
#0  0x00002aaaaacda71f in gdImageFlipVertical (im=0x602010) at gd_transform.c:26
#1  0x0000000000400d09 in main () at foo.cpp:38
(gdb) p *im
$8 = {
  pixels = 0x603cc0, 
  sx = 800, 
  sy = 800, 
  colorsTotal = 2, 
  red = {0, 255, 0 <repeats 254 times>}, 
  green = {0, 255, 0 <repeats 254 times>}, 
  blue = {0, 255, 0 <repeats 254 times>}, 
  open = {0, 0, 1 <repeats 254 times>}, 
  transparent = -1, 
  polyInts = 0x0, 
  polyAllocated = 0, 
  brush = 0x0, 
  tile = 0x0, 
  brushColorMap = {0 <repeats 256 times>}, 
  tileColorMap = {0 <repeats 256 times>}, 
  styleLength = 0, 
  stylePos = 0, 
  style = 0x0, 
  interlace = 0, 
  thick = 1, 
  alpha = {0 <repeats 256 times>}, 
  trueColor = 0, 
  tpixels = 0x0, 
  alphaBlendingFlag = 0, 
  saveAlphaFlag = 0, 
  AA = 0, 
  AA_color = 0, 
  AA_dont_blend = 0, 
  cx1 = 0, 
  cy1 = 0, 
  cx2 = 799, 
  cy2 = 799, 
  res_x = 96, 
  res_y = 96, 
  paletteQuantizationMethod = 0, 
  paletteQuantizationSpeed = 0, 
  paletteQuantizationMinQuality = 0, 
  paletteQuantizationMaxQuality = 0, 
  interpolation_id = GD_BILINEAR_FIXED, 
  interpolation = 0
}
(gdb)
```

If I had to guess, I'd say that there's some confusion between `im->pixels` and `im->tpixels`.
Hope this is helpful.

**Comment by smcdow** [comment]
Fixed with the following:
```
--- src/gd_transform.c.orig     2015-04-03 10:02:17.490524000 -0500
+++ src/gd_transform.c  2015-04-03 10:06:38.503886000 -0500
@@ -23,9 +23,9 @@
                unsigned char p;
                for (y = 0; y < im->sy / 2; y++) {
                        for (x = 0; x < im->sx; x++) {
-                               p = im->tpixels[y][x];
-                               im->tpixels[y][x] =     im->tpixels[im->sy - 1 - y][x];
-                               im->tpixels[im->sy - 1 - y][x] = p;
+                               p = im->pixels[y][x];
+                               im->pixels[y][x] =      im->pixels[im->sy - 1 - y][x];
+                               im->pixels[im->sy - 1 - y][x] = p;
                        }
                }
        }
```

**Comment by vapier** [comment]
thanks, i've merged this now!
