### ISSUE TITLE
2.2.4: Segfault in test suite.

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#357]
../config/test-driver: line 107:  2179 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: tiff/tiff_invalid_read

```
(gdb) bt
#0  0x00007f5b0af0a724 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007f5b0ca6a7ca in memcpy (__len=18446744073004923398, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string3.h:53
#2  dynamicGetbuf (ctx=<optimized out>, buf=<optimized out>, len=<optimized out>) at gd_io_dp.c:295
#3  0x00007f5b0ca702de in tiff_readproc (clientdata=<optimized out>, data=<optimized out>, size=<optimized out>) at gd_tiff.c:129
#4  0x00007f5b0b421226 in TIFFReadRawStrip1 () from /lib64/libtiff.so.5
#5  0x00007f5b0b421b3d in TIFFFillStrip () from /lib64/libtiff.so.5
#6  0x00007f5b0b421c86 in TIFFReadEncodedStrip () from /lib64/libtiff.so.5
#7  0x00007f5b0b4084e6 in gtStripContig () from /lib64/libtiff.so.5
#8  0x00007f5b0b40b845 in TIFFReadRGBAImageOriented () from /lib64/libtiff.so.5
#9  0x00007f5b0ca70fcd in createFromTiffRgba (im=0x55af642a6710, tif=0x55af642a50b0) at gd_tiff.c:775
#10 gdImageCreateFromTiffCtx (infile=infile@entry=0x55af642a5040) at gd_tiff.c:970
#11 0x00007f5b0ca7125d in gdImageCreateFromTiffPtr (size=<optimized out>, data=<optimized out>) at gd_tiff.c:1030
#12 0x000055af6278c29d in check_file (basename=<optimized out>) at tiff/tiff_invalid_read.c:32
#13 0x000055af6278c06c in main () at tiff/tiff_invalid_read.c:18

```

**Comment by remicollet** [comment]
Notice: only on x86_64 (no segfault on x86_64)

**Comment by remicollet** [comment]
Seems related to libtiff version.

Segfault doesn't occurs in RHEL-5 (libtiff 3.8.2) nor RHEL-6 (libtiff 3.9.4) but in RHEL-7 (libtiff 4.0.3) and Fedora  (libtiff 4.0.x)

And, as it occurs inside libtiff, not inside libgd, could be a libtiff issue.
